model_name: sis_tween
tensorboard_logs_dir: runs/
save_progress: true
save_interval: 10
num_workers: 16
batch_size: 16
distributed_enabled: true
image_size: 256
segmentator_score_threshold: 0.75
epochs: 50
