model_name: sis_tween
tensorboard_logs_dir: runs/
save_progress: true
save_interval: 10
num_workers: 16
batch_size: 8
distributed_enabled: false
world_size: 1
image_size: 256
segmentator_score_threshold: 0.1
